# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - "5.2"
    - "5.3"
    - "5.4"
    - "5.5"

# Specify versions of WordPress to test against (requires 3.8+)
# WP_VERSION is the WordPress tagged version (use "master" for SVN trunk)
env:
    - WP_VERSION=master
    - WP_VERSION=3.8

# Clones WordPress and configures our testing environment.
before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone https://github.com/tierra/wordpress.git /tmp/wordpress
    - mkdir -p "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cp -vR . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"

script: phpunit
